apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mongodb-chart.fullname" . }}-pvc
  labels:
    {{- include "mongodb-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
