apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.service.name }}
  name: {{ .Values.service.name }}
  namespace: prod
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.azureKeyVault.enabled }}
        secrets-store.csi.k8s.io/enable: "true"
        secrets-store.csi.k8s.io/secret-provider-class: "{{ include "service-chart.fullname" . }}-akv"
        {{- end }}
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
      - image: pipocwebapp.azurecr.io/{{ .Values.service.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
        name: {{ .Values.service.name }}
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
        {{- if .Values.azureKeyVault.enabled }}
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
        {{- end }}
        env:
        {{- range .Values.secrets }}
          - name: {{ .envVar }}
            valueFrom:
              secretKeyRef:
                name: {{ .name }}
                key: {{ .name }}
        {{- end }}
        {{- if .Values.azureKeyVault.enabled }}
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: {{ include "service-chart.fullname" . }}-akv-secret
                key: backend-mongodb-uri
          - name: CORS_ORIGIN
            valueFrom:
              secretKeyRef:
                name: {{ include "service-chart.fullname" . }}-akv-secret
                key: backend-cors-origin
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ .Values.configMapName }}
      serviceAccountName: prod
      volumes:
      {{- if .Values.azureKeyVault.enabled }}
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "service-chart.fullname" . }}-akv
      {{- end }}
