replicaCount: 1

image:
  repository: mongo
  tag: 8.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

persistence:
  enabled: true
  size: 1Gi

autoscaling:
  enabled: false

serviceAccount:
  create: false
  name: ""

azureKeyVault:
  enabled: false
  tenantId: "189d905e-849b-4745-ad7e-f7bf3c9d3aab"
  keyVaultName: "kv-pocpi-prod"
  objects:
    - objectName: "mongodb-admin-username"
      objectType: "secret"
      objectVersion: ""
    - objectName: "mongodb-admin-password"
      objectType: "secret"
      objectVersion: ""
